# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HospitalList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[object]=None):  # noqa: E501
        """HospitalList - a model defined in Swagger

        :param data: The data of this HospitalList.  # noqa: E501
        :type data: List[object]
        """
        self.swagger_types = {
            'data': List[object]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'HospitalList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HospitalList of this HospitalList.  # noqa: E501
        :rtype: HospitalList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[object]:
        """Gets the data of this HospitalList.


        :return: The data of this HospitalList.
        :rtype: List[object]
        """
        return self._data

    @data.setter
    def data(self, data: List[object]):
        """Sets the data of this HospitalList.


        :param data: The data of this HospitalList.
        :type data: List[object]
        """

        self._data = data
