openapi: 3.0.3
info:
  title: Swagger Hospital map - OpenAPI 3.0
  description: |-
    This is a hospital map API based on OpenAPI 3.0 specification
  version: 1.0.11
servers:
  - url: http://localhost/api/v1
tags:
  - name: hospital
    description: Hospital API
paths:
  /hospital:
    get:
      summary: Get list of hospital
      operationId: getHospitalList
      tags:
        - hospital
      parameters:
        - name: longitude
          required: false
          in: query
          schema:
            type: number
        - name: latitude
          required: false
          in: query
          schema:
            type: number
        - name: language
          required: false
          in: query
          schema:
            type: string
            enum: [en, ch, kr, esp, tw, de, translator]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HospitalList'
        '400':
          description: Invalid parameter supplied
        '500':
          description: Internal server error
  /hospital/{hospital_id}:
    get:
      summary: Get hospital detail
      description: Get hospital detail by `id`
      operationId: getHospital
      tags:
        - hospital
      parameters:
        - name: hospital_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: language
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hospital'
        '400':
          description: Invalid ID supplied
        '500':
          description: Internal server error
components:
  schemas:
    SupportedLanguages:
      type: array
      items:
        enum: [en, ch, kr, esp, tw, de, translator]
    Hospital:
      properties:
        id:
          type: integer
          format: int64
        longitude:
          type: number
        latitude:
          type: number
        name:
          type: string
        address:
          type: string
        supportedLanguages:
          $ref: '#/components/schemas/SupportedLanguages'
        examinationTypes:
          type: array
          items:
            type: string
        businessHours:
          type: array
          items:
            type: object
            properties:
              day:
                type: string
                enum: [sunday, monday, tuesday, wednesday, thursday, friday, saturday]
              from:
                type: string
              to:
                type: string
        postNumber:
          type: string
        telephone:
          type: string
        website:
          type: string
        
    HospitalList:
      properties:
        data:
          type: array
          items:
            type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            longitude:
              type: number
            latitude:
              type: number
            supportedLanguages:
              $ref: '#/components/schemas/SupportedLanguages'

