/*
 * Swagger Hospital map - OpenAPI 3.0
 * This is a hospital map API based on OpenAPI 3.0 specification
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HospitalBusinessHours model module.
 * @module model/HospitalBusinessHours
 * @version 1.0.11
 */
export class HospitalBusinessHours {
  /**
   * Constructs a new <code>HospitalBusinessHours</code>.
   * @alias module:model/HospitalBusinessHours
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HospitalBusinessHours</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HospitalBusinessHours} obj Optional instance to populate.
   * @return {module:model/HospitalBusinessHours} The populated <code>HospitalBusinessHours</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HospitalBusinessHours();
      if (data.hasOwnProperty('day'))
        obj.day = ApiClient.convertToType(data['day'], 'String');
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'String');
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>day</code> property.
 * @enum {String}
 * @readonly
 */
HospitalBusinessHours.DayEnum = {
  /**
   * value: "sunday"
   * @const
   */
  sunday: "sunday",

  /**
   * value: "monday"
   * @const
   */
  monday: "monday",

  /**
   * value: "tuesday"
   * @const
   */
  tuesday: "tuesday",

  /**
   * value: "wednesday"
   * @const
   */
  wednesday: "wednesday",

  /**
   * value: "thursday"
   * @const
   */
  thursday: "thursday",

  /**
   * value: "friday"
   * @const
   */
  friday: "friday",

  /**
   * value: "saturday"
   * @const
   */
  saturday: "saturday"
};
/**
 * @member {module:model/HospitalBusinessHours.DayEnum} day
 */
HospitalBusinessHours.prototype.day = undefined;

/**
 * @member {String} from
 */
HospitalBusinessHours.prototype.from = undefined;

/**
 * @member {String} to
 */
HospitalBusinessHours.prototype.to = undefined;

