/*
 * Swagger Hospital map - OpenAPI 3.0
 * This is a hospital map API based on OpenAPI 3.0 specification
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HospitalList model module.
 * @module model/HospitalList
 * @version 1.0.11
 */
export class HospitalList {
  /**
   * Constructs a new <code>HospitalList</code>.
   * @alias module:model/HospitalList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HospitalList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HospitalList} obj Optional instance to populate.
   * @return {module:model/HospitalList} The populated <code>HospitalList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HospitalList();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [Object]);
    }
    return obj;
  }
}

/**
 * @member {Array.<Object>} data
 */
HospitalList.prototype.data = undefined;

