/*
 * Swagger Hospital map - OpenAPI 3.0
 * This is a hospital map API based on OpenAPI 3.0 specification
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Hospital} from '../model/Hospital';
import {HospitalList} from '../model/HospitalList';

/**
* Hospital service.
* @module api/HospitalApi
* @version 1.0.11
*/
export class HospitalApi {

    /**
    * Constructs a new HospitalApi. 
    * @alias module:api/HospitalApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getHospital operation.
     * @callback moduleapi/HospitalApi~getHospitalCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Hospital{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get hospital detail
     * Get hospital detail by &#x60;id&#x60;
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.language 
     * @param {module:api/HospitalApi~getHospitalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getHospital(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getHospital");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'language': opts['language']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/xml'];
      let returnType = Hospital;

      return this.apiClient.callApi(
        '/hospital/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getHospitalList operation.
     * @callback moduleapi/HospitalApi~getHospitalListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HospitalList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list of hospital
     * @param {Object} opts Optional parameters
     * @param {Number} opts.longitude 
     * @param {Number} opts.latitude 
     * @param {module:api/HospitalApi~getHospitalListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getHospitalList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'longitude': opts['longitude'],'latitude': opts['latitude']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/xml'];
      let returnType = HospitalList;

      return this.apiClient.callApi(
        '/hospital', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}